# Generated by Django 5.1.5 on 2025-10-26 10:08

from django.db import migrations, models
from django.core.validators import MinValueValidator, MaxValueValidator
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movie_vote_average"),
    ]

    operations = [
        # Add timestamp fields
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, help_text='When this record was last updated'),
            preserve_default=False,
        ),
        
        # Update field types and add validators
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.PositiveIntegerField(blank=True, help_text='The movie\'s budget in USD', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='homepage',
            field=models.URLField(blank=True, help_text='Official movie website URL', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True, help_text='A brief description of the movie plot', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Popularity score', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, help_text='The date the movie was released', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.PositiveBigIntegerField(blank=True, help_text='The movie\'s total revenue in USD', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.PositiveIntegerField(blank=True, help_text='Movie runtime in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(blank=True, help_text='The movie\'s tagline or slogan', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, help_text='The title of the movie', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average user rating (0-10)', max_digits=4, null=True, validators=[MinValueValidator(0), MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_count',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of votes', null=True),
        ),
        
        # Add movie_status choices
        migrations.AlterField(
            model_name='movie',
            name='movie_status',
            field=models.CharField(blank=True, choices=[('Released', 'Released'), ('Post Production', 'Post Production'), ('In Production', 'In Production'), ('Planned', 'Planned'), ('Rumored', 'Rumored'), ('Canceled', 'Canceled')], help_text='Current status of the movie', max_length=50, null=True),
        ),
        
        # Add database indexes
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS movies_movie_title_idx ON movies_movie (title);",
            reverse_sql="DROP INDEX IF EXISTS movies_movie_title_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS movies_movie_release_date_idx ON movies_movie (release_date);",
            reverse_sql="DROP INDEX IF EXISTS movies_movie_release_date_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS movies_movie_vote_average_idx ON movies_movie (vote_average);",
            reverse_sql="DROP INDEX IF EXISTS movies_movie_vote_average_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS movies_movie_popularity_idx ON movies_movie (popularity);",
            reverse_sql="DROP INDEX IF EXISTS movies_movie_popularity_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS movies_movie_movie_status_idx ON movies_movie (movie_status);",
            reverse_sql="DROP INDEX IF EXISTS movies_movie_movie_status_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS movies_movie_created_at_idx ON movies_movie (created_at);",
            reverse_sql="DROP INDEX IF EXISTS movies_movie_created_at_idx;"
        ),
    ]
